### ISSUE TITLE
Granting admin perms on wrong server?

### ISSUE THREAD

**Issue by mattferris** [smonaica/samba-ad-dc#37]
Following the Creating Shares doc and ran into an issue with the two commands to grant perms (my domain is ALPHA):

```
fs1 # net rpc rights grant "ALPHA\Domain Admins" SeDiskOperatorPrivilege -U "ALPHA\Administrator"
Enter ALPHA\Administrator's password:
Could not connect to server 127.0.0.1
The username or password was not correct.
Connection failed: NT_STATUS_LOGON_FAILURE
```

The context of the document is creating shares on FS1, so that's where I attempted to issue the commands. Seeing as I already granted `SeDiskOperatorPrivilege` to `Domain Admins` when joining FS1 to the domain, I thought maybe the two commands were supposed to be run on DC1 instead? This is what I did, and the commands ran successfully.

Are these grants supposed to be completed on DC1 or FS1?

**Comment by lukebarone** [comment]
Supposed to be on the file server. Can you run net rpc rights list
SeDiskOperatorPrivilege -U Alpha/Administrator

And let me know what it shows (take care about the slash)

On Jul 21, 2017 12:34 PM, "Matt Ferris" <notifications@github.com> wrote:

Following the Creating Shares doc and ran into an issue with the two
commands to grant perms:

fs1 # net rpc rights grant "ALPHA\Domain Admins"
SeDiskOperatorPrivilege -U "ALPHA\Administrator"
Enter ALPHA\Administrator's password:
Could not connect to server 127.0.0.1
The username or password was not correct.
Connection failed: NT_STATUS_LOGON_FAILURE

The context of the document is creating shares on FS1, so that's where I
attempted to issue the commands. Seeing as I already granted
SeDiskOperatorPrivilege to Domain Admins when joining FS1 to the domain, I
thought maybe the two commands were supposed to be run on DC1 instead? This
is what I did, and the commands ran successfully.

Are these grants supposed to be completed on DC1 or FS1?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/smonaica/samba-ad-dc/issues/37>, or mute the thread

**Comment by mattferris** [comment]
Ah, you know what? I'm dumb. I'm using snapshots to allow me to replay things like joins and such to test firewall rules. I forgot that this particular snapshot didn't follow the rest of the 'Add Member Server' doc. If I do what I'm told in the doc, then everything works well.

Thanks!
